apiVersion: v1
kind: Service
metadata:
  name: mllpserver-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 1080
    targetPort: 1080
    protocol: TCP
  selector:
    app: mllpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mllpserver-deployment
  labels:
    app: mllpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mllpserver
  template:
    metadata:
      labels:
        app: mllpserver
    spec:
      containers:
      - name: mllpserver
        image: acrhl7.azurecr.io/hl7/mllpserver:latest
        ports:
        - containerPort: 1080
          protocol: TCP