name: Build MLLP Server

on:
  push:
   paths:
     - 'src/MllP/mllpServer/**'
  workflow_dispatch:

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}               
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}      

      - name: Build docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_SERVER }}/mlppserver:${{ github.sha }} .
        working-directory: ./src/MllP/mllpServer  

      - name: Deploy to container registry
        run: |
          docker push ${{ secrets.REGISTRY_SERVER }}/mlppserver:${{ github.sha }}
        working-directory: ./src/MllP/mllpServer  

  deploy:
    needs: build
    name: Deploy container app
    
    runs-on: ubuntu-latest
    
    steps:     

      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: 'rg-aca-lb'                    
          template: ./bicep/mllpServer.bicep
          parameters: containerEnvironmentName=${{ secrets.ACA_ENV_NAME }} image=${{ secrets.REGISTRY_SERVER }}/mlppserver:${{ github.sha }} azureContainerRegistry=${{ secrets.REGISTRY_SERVER }}  azureContainerRegistryUsername=${{ secrets.REGISTRY_USERNAME }} azureContainerRegistryPassword=${{ secrets.REGISTRY_PASSWORD }}